apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cert-manager/production
  prune: true
  validation: client
# resources:
#   - ../base/cert-manager
# patchesStrategicMerge:
#   - cert-manager-values.yaml