apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yaml
  - letsencrypt-staging.yaml
  - letsencrypt-production.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml