apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  values:
    installCRDs: true
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: cert-manager
  #     namespace: cert-manager